### ISSUE TITLE
Numba RuntimeError: cannot cache function '_make_tree'

### ISSUE THREAD

**Issue by flangopink** [deadmanIsARabbit/RimworldAvatarToStableDiffusion#2]
Trying to generate an avatar using a local SD, getting this error before it even starts generating. Adding a NUMBA_CACHE_DIR environment variable didn't seem to help.
```
AI-gen process failed with the following error:
  Traceback (most recent call last):
    File "Avatar2SD.py", line 5, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
    File "rembg\__init__.py", line 5, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
    File "rembg\bg.py", line 17, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
    File "pymatting\__init__.py", line 2, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
    File "pymatting\util\__init__.py", line 2, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
    File "pymatting\util\kdtree.py", line 8, in <module>
    File "numba\core\decorators.py", line 225, in wrapper
    File "numba\core\dispatcher.py", line 808, in enable_caching
    File "numba\core\caching.py", line 601, in __init__
    File "numba\core\caching.py", line 337, in __init__
  RuntimeError: cannot cache function '_make_tree': no locator available for file 'pymatting\\util\\kdtree.py'
  [PYI-13664:ERROR] Failed to execute script 'Avatar2SD' due to unhandled exception!
```

**Comment by deadmanIsARabbit** [comment]
Hi @flangopink thank you for your submission. 

Are you on Windows or Linux right now?
Because if you are on Windows then please use the .exe from within the [release](https://github.com/deadmanIsARabbit/RimworldAvatarToStableDiffusion/releases/download/v1.0.4.1/Avatar2SDv1.0.4.1.zip) instead of the python script file.

**Comment by flangopink** [comment]
Yes i'm on Windows and was using the .exe from that exact release and got this error.

**Comment by deadmanIsARabbit** [comment]
@flangopink I was using Python 3.10.6 to create the .exe file. 
I've just released a new Version using Python 3.13.2 and a venv this time. Would you mind to test the new release [v1.0.4.2](https://github.com/deadmanIsARabbit/RimworldAvatarToStableDiffusion/releases/tag/v1.0.4.2) please?

**Comment by flangopink** [comment]
Still getting the same error on latest release, unfortunately.

**Comment by deadmanIsARabbit** [comment]
I'm sorry. I have no more idea. 
What you could try is to run the exe from the command line. 
```
X:\PATH\TO\THE\Avatar2SD.exe "X:\PATH\TO\AN\AVATAR\Image.png" "ANY PROMPT"
```
And publish the whole output here. 
Maybe this will give us some usefull logs. 
If this still fails at rembg i will publish a new version where the rembg is optional. 
Deal?
